export const LOCAL_LOGIN = 'LOCAL_LOGIN'
export const LOCAL_LOGOUT = 'LOCAL_LOGOUT'

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'

// 审核中心 会员认证
export const MEMBER_LIST_AWAIT = 'MEMBER_LIST_AWAIT'
export const MEMBER_LIST_AUDITING = 'MEMBER_LIST_AUDITING'
export const MEMBER_LIST_AUDITING_FAIL = 'MEMBER_LIST_AUDITING_FAIL'

//首页
export const DASHBOARD_MEMBER = 'DASHBOARD_MEMBER'
export const DASHBOARD_APP = 'DASHBOARD_APP'


//会员
export const MEMBER_COUNT = 'MEMBER_COUNT'
export const MEMBER_RANK_LIST = 'MEMBER_RANK_LIST'
export const MEMBER_APP_STATISTIC = 'MEMBER_APP_STATISTIC'
export const CONSUME_DURATION_STATISTIC = 'CONSUME_DURATION_STATISTIC'

//应用
export const APP_COUNT = 'APP_COUNT'
export const LASTDAY_COMSUME = 'LASTDAY_COMSUME'
export const LASTDAY_DURATION = 'LASTDAY_DURATION'

//租户
export const TENANT_LIST = 'TENANT_LIST'
export const TENANT_MORE_LIST = 'TENANT_MORE_LIST'
export const TENANT_CERT = 'TENANT_CERT'
export const TENANT_BILLING = 'TENANT_BILLING'
export const TENANT_INDICANT = 'TENANT_INDICANT'
export const TENANT_INFO = 'TENANT_INFO'
export const TENANT_AUTH_INFO = 'TENANT_AUTH_INFO'
export const TENANT_DURATION_STATISTIC = 'TENANT_DURATION_STATISTIC'
export const TENANT_API_STATISTIC = 'TENANT_API_INVOKE '
export const TENANT_SESSION_STATISTIC = 'TENANT_SESSION_STATISTIC '



//消息中心
export const MESSAGE_LIST = 'MESSAGE_LIST'
export const MESSAGE_MORE_LIST = 'MESSAGE_MORE_LIST'
export const NEW_MESSAGE = 'NEW_MESSAGE'
export const EDIT_MESSAGE = 'EDIT_MESSAGE'
export const MESSAGE_DETAIL = 'MESSAGE_DETAIL'
export const MESSAGE_NUM = 'MESSAGE_NUM'

//客服中心
export const SERVICE_LIST = 'SERVICE_LIST'
export const SERVICE_MORE_LIST = 'SERVICE_MORE_LIST'

//财务中心
export const INVOICE_PENDING_LIST = 'INVOICE_PENDING_LIST'
export const INVOICE_MORE_PENDING_LIST = 'INVOICE_MORE_PENDING_LIST'
export const INVOICE_PASSED_LIST = 'INVOICE_PASSED_LIST'
export const INVOICE_MORE_PASSED_LIST = 'INVOICE_MORE_PASSED_LIST'
export const INVOICE_ABNORMAL_LIST = 'INVOICE_ABNORMAL_LIST'
export const INVOICE_MORE_ABNORMAL_LIST = 'INVOICE_MORE_ABNORMAL_LIST'
export const INVOICE_DETAIL = 'INVOICE_DETAIL'

export const DELIVERY_UNSEND_LIST = 'DELIVERY_UNSEND_LIST'
export const DELIVERY_MORE_UNSEND_LIST = 'DELIVERY_MORE_UNSEND_LIST'
export const DELIVERY_SEND_LIST = 'DELIVERY_SEND_LIST'
export const DELIVERY_MORE_SEND_LIST = 'DELIVERY_MORE_SEND_LIST'
export const DELIVERY_DETAIL = 'DELIVERY_DETAIL'

//审核中心
export const DEMAND_AWAIT_LIST = 'DEMAND_AWAIT_LIST'
export const DEMAND_MORE_PENDING_LIST = 'DEMAND_MORE_PENDING_LIST'
export const DEMAND_AUDITING_LIST = 'DEMAND_AUDITING_LIST'
export const DEMAND_MORE_AUDITING_LIST = 'DEMAND_MORE_AUDITING_LIST'
export const DEMAND_UNAUTH_LIST = 'DEMAND_UNAUTH_LIST'
export const DEMAND_MORE_UNAUTH_LIST = 'DEMAND_MORE_UNAUTH_LIST'
export const DEMAND_DETAIL = 'DEMAND_DETAIL'


//放音文件
export const VOICE_AWAIT_LIST = 'VOICE_AWAIT_LIST'
export const VOICE_MORE_PENDING_LIST = 'VOICE_MORE_PENDING_LIST'
export const VOICE_AUDITING_LIST = 'VOICE_AUDITING_LIST'
export const VOICE_MORE_AUDITING_LIST = 'VOICE_MORE_AUDITING_LIST'
export const VOICE_UNAUTH_LIST = 'VOICE_UNAUTH_LIST'
export const VOICE_MORE_UNAUTH_LIST = 'VOICE_MORE_UNAUTH_LIST'
export const VOICE_DETAIL = 'VOICE_DETAIL'


